name: state_notifier
description: ValueNotifier, but outside Flutter and with some extra perks
version: 0.7.0
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  coverage: ^0.14.2
  matcher: ^0.12.6
  mockito: ^4.1.1
  test: ^1.12.0
  # test_coverage: ^0.4.1
